Repository CSCfi/beacon-python, pull requests merged in 2019-03, with the labels that each got.

#75 Sanitize db query input
  beacon_api/utils/data_query.py
  deploy/test/integ_test.py
  tests/test_data_query.py
Labels: bug

#76 Fix typos and dated information in docs
  CONTRIBUTING.md
  docs/deploy.rst
  docs/example.rst
  docs/testing.rst
Labels: documentation

#78 Acknowledgements
  README.md
  beacon_api/utils/validate.py
Labels: documentation

#79 Add coordinates to response
  beacon_api/schemas/response.json
  beacon_api/utils/data_query.py
  deploy/test/integ_test.py
  docs/example.rst
  tests/test_data_query.py
Labels: enhancement

#80 Fix callCount
  data/init.sql
Labels: bug
