Repository CSCfi/beacon-python, pull requests merged in 2019-06, with the labels that each got.

#104 Specifying license in docs
  README.md
  docs/index.rst
Labels: documentation

#106 Hotfix for breaking changes in ELIXIR AAI
  beacon_api/conf/__init__.py
  beacon_api/conf/config.ini
  beacon_api/utils/validate.py
  deploy/test/auth_test.ini
Labels: bug

#105 GA4GH Permissions Module
  beacon_api/permissions/ga4gh.py
  beacon_api/utils/validate.py
  tests/test_basic.py
Labels: ga4gh

#114 Update contributions to highlight dev branch
  CONTRIBUTING.md
Labels: documentation

#115 Update token format
  beacon_api/permissions/ga4gh.py
  tests/test_basic.py
Labels: bug, ga4gh

#120 Update GA4GH service-info
  beacon_api/api/info.py
  deploy/test/integ_test.py
Labels: ga4gh
