Repository CSCfi/beacon-python, pull requests merged in 2019-04, with the labels that each got.

#81 Add handover
  beacon_api/__init__.py
  beacon_api/api/info.py
  beacon_api/api/query.py
  beacon_api/conf/__init__.py
  beacon_api/conf/config.ini
  beacon_api/schemas/info.json
  beacon_api/schemas/response.json
  beacon_api/utils/data_query.py
  deploy/test/auth_test.ini
  tests/test_data_query.py
Labels: enhancement

#83 Cleanup and update documentation
  .gitignore
  README.md
  docs/db.rst
  docs/deploy.rst
  docs/index.rst
  docs/instructions.rst
  docs/permissions.rst
  requirements.txt
  tests/test_app.py
  tests/test_response.py
Labels: documentation

#84 Moved handover to extension module
  .gitignore
  beacon_api/api/info.py
  beacon_api/api/query.py
  beacon_api/extensions/__init__.py
  beacon_api/extensions/handover.py
  beacon_api/utils/data_query.py
  beacon_api/utils/validate.py
  deploy/Dockerfile
  deploy/docker-compose.yml
  deploy/test/docker-compose.yml
  deploy/test/integ_test.py
  docs/code.rst
  docs/optionals.rst
  docs/permissions.rst
  setup.py
  tests/test_data_query.py
Labels: documentation, enhancement

#85 Adding support for mateName
  beacon_api/api/query.py
  beacon_api/conf/config.ini
  beacon_api/extensions/__init__.py
  beacon_api/extensions/mate_name.py
  beacon_api/schemas/info.json
  beacon_api/schemas/query.json
  beacon_api/schemas/response.json
  beacon_api/utils/data_query.py
  beacon_api/utils/db_load.py
  data/init.sql
  docs/code.rst
  docs/db.rst
  docs/optionals.rst
  setup.py
  tests/test_data_query.py
  tests/test_db_load.py
  tests/test_mate_name.py
  tests/test_response.py
Labels: enhancement, release

#88 Use enum for accessType
  beacon_api/extensions/mate_name.py
  beacon_api/utils/data_query.py
  data/init.sql
Labels: enhancement

#89 Avoid coalesce on fields that need index search
  beacon_api/utils/data_query.py
Labels: enhancement
