Repository CSCfi/beacon-python, pull requests merged in 2019-05, with the labels that each got.

#91 Simplify query for all and miss
  beacon_api/extensions/mate_name.py
  beacon_api/utils/data_query.py
  deploy/test/integ_test.py
Labels: enhancement

#92 Tests and Docs updates
  docs/db.rst
  docs/deploy.rst
  docs/permissions.rst
  tests/test_data_query.py
  tests/test_db_load.py
  tests/test_mate_name.py
Labels: documentation, testing

#93 Make matename work
  beacon_api/api/query.py
  beacon_api/extensions/mate_name.py
  beacon_api/schemas/query.json
  deploy/test/docker-compose.yml
  deploy/test/integ_test.py
  deploy/test/mate.sql
Labels: bug, testing

#96 Automating checks for security, documentation and more
  .bandit.yml
  .travis.yml
  beacon_api/app.py
  beacon_api/conf/config.py
  beacon_api/extensions/mate_name.py
  beacon_api/utils/data_query.py
  beacon_api/utils/validate.py
  deploy/test/integ_test.py
  deploy/test/run_tests.py
  docs/db.rst
  docs/instructions.rst
  docs/permissions.rst
  docs/testing.rst
  tests/requirements.txt
  tox.ini
Labels: testing

#99 Fix for readthedocs
  docs/docs.txt
  readthedocs.yml
Labels: bug

#101 Aligning Beacon with GA4GH standards
  .github/PULL_REQUEST_TEMPLATE.md
  beacon_api/__init__.py
  beacon_api/api/info.py
  beacon_api/app.py
  beacon_api/conf/__init__.py
  beacon_api/conf/config.ini
  deploy/test/auth_test.ini
  deploy/test/integ_test.py
  docs/instructions.rst
  docs/permissions.rst
  tests/test_app.py
Labels: ga4gh

#102 Docs updates for next release
  README.md
  beacon_api/api/__init__.py
  beacon_api/conf/config.ini
  deploy/test/auth_test.ini
  docs/example.rst
Labels: release

#103 Fix shifted line numbers
  docs/code.rst
  docs/instructions.rst
  docs/optionals.rst
Labels: bug
