Repository CSCfi/beacon-python, pull requests merged in 2019-02, with the labels that each got.

#61 More integration tests
  README.md
  beacon_api/utils/validate.py
  deploy/test/integ_test.py
  deploy/test/mock_auth.py
  docs/conf.py
  docs/index.rst
  docs/instructions.rst
  docs/permissions.rst
  docs/static/custom.css
  docs/testing.rst
Labels: documentation, testing

#62 beacon_init optimisation
  beacon_api/utils/db_load.py
  deploy/test/integ_test.py
  tests/test_db_load.py
Labels: bug, performance

#63 Add Required 401 header
  beacon_api/api/exceptions.py
  beacon_api/api/query.py
  beacon_api/utils/validate.py
  deploy/test/integ_test.py
Labels: enhancement

#64 Optimise init load in DB for parsing VCF file
  beacon_api/utils/db_load.py
  tests/test_basic.py
  tests/test_db_load.py
Labels: enhancement

#65 Addressing unproper del and ins
  beacon_api/utils/db_load.py
  tests/test_db_load.py
Labels: bug

#66 Readable docs
  beacon_api/__init__.py
  beacon_api/conf/__init__.py
  beacon_api/conf/config.ini
  beacon_api/conf/config.py
  beacon_api/permissions/__init__.py
  beacon_api/utils/__init__.py
  docs/deploy.rst
  docs/example.rst
  docs/index.rst
  docs/instructions.rst
  docs/permissions.rst
Labels: documentation

#70 Add missing variantType MNP to schema
  beacon_api/schemas/info.json
  beacon_api/schemas/query.json
  beacon_api/schemas/response.json
  tests/coveralls.py
Labels: bug

#71 JSON schema Start params
  Pipfile
  beacon_api/api/exceptions.py
  beacon_api/api/info.py
  beacon_api/api/query.py
  beacon_api/schemas/query.json
  beacon_api/schemas/response.json
  deploy/test/integ_test.py
  requirements.txt
  setup.py
  tests/test_app.py
  tests/test_basic.py
Labels: bug, enhancement, testing

#73 Code cleanup
  beacon_api/api/info.py
  beacon_api/api/query.py
  beacon_api/app.py
  beacon_api/permissions/rems.py
  beacon_api/utils/data_query.py
  beacon_api/utils/db_load.py
  beacon_api/utils/validate.py
  deploy/test/integ_test.py
  docs/code.rst
  docs/deploy.rst
  docs/example.rst
  docs/index.rst
  docs/permissions.rst
  setup.py
  tests/test_app.py
  tests/test_basic.py
Labels: documentation, release, testing
